### ISSUE TITLE
left-ear Animation

### ISSUE THREAD

**Issue by trebird** [trebird/interactive-svg#1]
I have an animation that moves the left-eye, but Markbot says the left eye doesn't move with the animation. It's un**bear**able!

I know keyframes/transition settings still need playing around with, but I'm not sure how to fix the functionality issue and wonder if you could nudge me in the right direction or tell me to keep digging if it's obvious.

Thank you!
Treawna

**Comment by trebird** [comment]
Figured it out!

**Comment by charlie-quinn** [comment]
Hey @trebird this issue is still popping up inside of my **mentioned issues list**. I'm not sure why this is, but could you try removing my name above please? Hopefully that works. 🙌

**Comment by trebird** [comment]
Weird! Just deleted the tag, so hopefully it stops popping up. Let me know if there are any **_issues_**  😏🐻
